#!/bin/bash

# From https://unix.stackexchange.com/questions/382817/uefi-bios-bootable-live-debian-stretch-amd64-with-persistence

if [[ ${EUID} -ne 0 ]]; then
  echo "this script must be executed with elevated privileges"
  exit 1
fi

iso=$1
dev=$2

if [[ -z "${iso}" || ! -f ${iso} || ! -s ${iso} ]]; then
  echo "parameter 1 must be source ISO image"
  exit 1
fi

if [[ -z "${dev}" || ! -b ${dev} ]]; then
  echo "param 2 must be target block device"
  exit 1
fi

echo "unmounting old partitions"
umount ${dev}*

sleep 1

dd if=/dev/zero of=${dev} bs=1M count=16 iflag=fullblock

sleep 1

echo "creating partitions"
parted ${dev} --script mktable msdos
parted ${dev} --script mkpart primary fat16 1MiB 3GiB
parted ${dev} --script mkpart primary ext4 3GiB 100%
parted ${dev} --script set 1 boot on

echo "syncing and probing new paritions"
sync
partprobe

sleep 1

echo "creating file systems"
mkfs.vfat -n LIVE ${dev}1
mkfs.ext4 -m 0 -F -L persistence -E lazy_itable_init=0,lazy_journal_init=0 ${dev}2

echo "creating temporary mount locations"
tmp=$(mktemp --tmpdir --directory debianlive.XXXXX)
tmplive=${tmp}/live
tmppersistence=${tmp}/persistence
tmpiso=${tmp}/iso
tmpall="${tmplive} ${tmppersistence} ${tmpiso}"

echo "mounting resources"
mkdir ${tmpall}
mount ${dev}1 ${tmplive}
mount ${dev}2 ${tmppersistence}
mount -oro ${iso} ${tmpiso}

echo "copying iso image filesystem contents"
cp -ar ${tmpiso}/* ${tmplive}
sync

echo "creating persistence.conf"
echo "/ union" > ${tmppersistence}/persistence.conf

echo "installing grub"
grub-install --target=i386-pc --boot-directory=${tmplive}/boot/ ${dev}

echo "installing syslinux"
dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/mbr/gptmbr.bin of=${dev}
syslinux --install ${dev}2

echo "fixing isolinux folder/files"
mv ${tmplive}/isolinux ${tmplive}/syslinux
mv ${tmplive}/syslinux/isolinux.bin ${tmplive}/syslinux/syslinux.bin
mv ${tmplive}/syslinux/isolinux.cfg ${tmplive}/syslinux/syslinux.cfg

echo "fixing grub splash screen"
sed --in-place 's#isolinux/splash#syslinux/splash#' ${tmplive}/boot/grub/grub.cfg

echo "configuring persistence kernel parameter"
sed --in-place '0,/boot=live/{s/\(boot=live .*\)$/\1 persistence/}' ${tmplive}/boot/grub/grub.cfg ${tmplive}/syslinux/menu.cfg

echo "configuring keyboard layout and locales"
sed --in-place '0,/boot=live/{s/\(boot=live .*\)$/\1 keyboard-layouts=de locales=en_US.UTF-8,de_DE.UTF-8/}' ${tmplive}/boot/grub/grub.cfg ${tmplive}/syslinux/menu.cfg

echo "cleaning up"
umount ${tmpall}
rmdir ${tmpall} ${tmp}
